image: commandemy/ansible-cicd:latest

services:
  - docker:19.03.1-dind

stages:
  - lint
  - test
  
before_script:
  - export ANSIBLE_CONFIG=ansible.cfg
  - ansible --version
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa gitlab.commandemy.training >> ~/.ssh/known_hosts

build:
  stage: test
  script:
    - mkdir roles
    - ansible-galaxy install --force -r requirements.yml
    - ansible-playbook loadbalancer.yml
